#!/usr/bin/env perl
# vim:ft=perl:sts=4:sw=4:et

use v5.36;

use Proj;

say Proj->version();

my $src = "EPSG:4326";
my $tgt = "+proj=utm +zone=32 +datum=WGS84";
my $p = Proj->crs2crs($src,$tgt);
say $p->definition;
$p = $p->norm;
say $p->definition;

my $a = [12, 55];
my $b = $p->fwd($a);
printf "\neasting: %.3f, northing: %.3f\n", @$b;

printf "\neasting: %.3f, northing: %.3f\n", @{$p->fwd($a)};

my $c = $p->inv($b);
printf "\nlongitude: %g, latitude: %g\n", @$c;

my $d = $p->inv($p->fwd($a));
printf "\nlongitude: %g, latitude: %g\n", @$d;


