#!/usr/bin/env perl
# vim:ft=perl:sts=4:sw=4:et

use v5.36;

use Proj;

say Proj::version();

my $src = "EPSG:4326";
my $tgt = "+proj=utm +zone=32 +datum=WGS84";
my $p = Proj::crs2crs($src,$tgt);
say Proj::definition($p);
$p = Proj::norm($p);
say Proj::definition($p);

my $a = [12, 55];
my $b = Proj::fwd($p, $a);
printf "\neasting: %.3f, northing: %.3f\n", @$b;

printf "\neasting: %.3f, northing: %.3f\n", @{Proj::fwd($p,$a)};

my $c = Proj::inv($p, $b);
printf "\nlongitude: %g, latitude: %g\n", @$c;

my $d = Proj::inv($p, Proj::fwd($p,$a));
printf "\nlongitude: %g, latitude: %g\n", @$d;


