#!/usr/bin/env perl
# vim:ft=perl:sts=4:sw=4:et

use v5.36;

use Proj;

# requires Australian data
# projsync --system-directory --area-of-use Australia

my $zone = 56;
my $pos  = [502810, 6964520, 0];
say "@$pos\n";

say "mga to geographic gda94";

my $cs = Proj::crs2crs("EPSG:283".$zone, "EPSG:4283");
say Proj::definition($cs);
#$cs = Proj::norm($cs);
say Proj::definition($cs);
my $result = Proj::fwd($cs,$pos);
printf "%.9f %.9f %.3f\n", @$result;
my $result2 = Proj::inv($cs,$result);
printf "%.5f %.5f %.3f\n\n", @$result2;

say "mga to geographic gda2020 same";

$cs = Proj::crs2crs("EPSG:78".$zone, "EPSG:7844");
say Proj::definition($cs);
$cs = Proj::norm($cs);
say Proj::definition($cs);
$result = Proj::fwd($cs, $pos);
printf "%.9f %.9f %.3f\n", @$result;
$result2 = Proj::inv($cs, $result);
printf "%.5f %.5f %.3f\n\n", @$result2;

say "mga to mga gda94 to gda2020 helmert?";

$cs = Proj::crs2crs("EPSG:283".$zone, "EPSG:78".$zone);
say Proj::definition($cs);
$result = Proj::fwd($cs,$pos);
say Proj::definition($cs);
printf "%.3f %.3f %.3f\n\n", @$result;

say "mga to mga gda94 to gda2020 gridshift";

my $S = "+proj=pipeline +zone=".$zone." +south +ellps=GRS80";
$S .= " +step +inv +proj=utm";
$S .= " +step +proj=hgridshift +grids=au_icsm_GDA94_GDA2020_conformal.tif";
$S .= " +step +proj=utm";
$cs = Proj::create($S);
say Proj::definition($cs);
$result = Proj::fwd($cs,$pos);
printf "%.3f %.3f %.3f\n\n", @$result;

say "mga eht to ahd ausgeoid09 using 3steps";

my $mga2gda = Proj::crs2crs("epsg:283".$zone, "epsg:4283");
my $gda2ahd = Proj::crs2crs("epsg:4939", "epsg:9464");
$result     = Proj::inv($mga2gda, Proj::fwd($gda2ahd, Proj::fwd($mga2gda, $pos)));
say Proj::definition($mga2gda);
say Proj::definition($gda2ahd);
printf "%.3f %.3f %.3f\n\n", @$result;

say "mga eht to ahd ausgeoid2020 using 3steps";

$mga2gda = Proj::crs2crs("epsg:78".$zone, "epsg:7844");
$gda2ahd = Proj::crs2crs("epsg:7843", "epsg:9463");
$result  = Proj::inv($mga2gda, Proj::fwd($gda2ahd, Proj::fwd($mga2gda, $pos)));
say Proj::definition($mga2gda);
say Proj::definition($gda2ahd);
printf "%.3f %.3f %.3f\n\n", @$result;

